name: Hank Quinlan, Horrible Cop
markdown: kramdown

collections:
  library:
    output: true
    permalink: /:path/:name/:output_ext
  blog:
    output: true
plugins:
  - jekyll-redirect-from
defaults:
  - scope:
      path: "_library/Web"
    values:
      layout: "web_tutorial"

